In [1]:
import numpy as np
import pandas as pd
from collections import Counter

In [3]:
with open("../yelp_dataset/yelp_academic_dataset_business21.json", "r") as f21:
    df21 = pd.read_json(f21, orient="records", lines=True)

In [4]:
df_p = df21[df21['city'] =='Philadelphia']

In [1]:
df_p.review_count

NameError: name 'df_p' is not defined

In [4]:
df_p.to_csv("phily.csv", index = False)

In [9]:
df21.city.nunique()

1416

In [6]:
Counter(df21.city).most_common(10)

[('Philadelphia', 14569),
 ('Tucson', 9250),
 ('Tampa', 9050),
 ('Indianapolis', 7540),
 ('Nashville', 6971),
 ('New Orleans', 6209),
 ('Reno', 5935),
 ('Edmonton', 5054),
 ('Saint Louis', 4827),
 ('Santa Barbara', 3829)]

In [8]:
with open("../yelp_dataset/yelp_academic_dataset_business20.json", "r") as f20:
    df20 = pd.read_json(f20, orient="records", lines=True)

In [10]:
with open("../yelp_dataset/yelp_academic_dataset_business19.json", "r") as f19:
    df19 = pd.read_json(f19, orient="records", lines=True)

In [ ]:
with open("../yelp_dataset/yelp_academic_dataset_business18.json", "r") as f18:
    df18 = pd.read_json(f18, orient="records", lines=True)

In [22]:
Counter(df18.city).most_common(10)

NameError: name 'df18' is not defined

In [21]:
Counter(df19.city).most_common(15)

[('Las Vegas', 31631),
 ('Toronto', 20366),
 ('Phoenix', 20171),
 ('Charlotte', 10422),
 ('Scottsdale', 9342),
 ('Calgary', 8377),
 ('Pittsburgh', 7630),
 ('Montr√©al', 6979),
 ('Mesa', 6577),
 ('Henderson', 5272)]

In [14]:
Counter(df20.city).most_common(10)

[('Austin', 22416),
 ('Portland', 18203),
 ('Vancouver', 13330),
 ('Atlanta', 12612),
 ('Orlando', 10637),
 ('Boston', 8263),
 ('Columbus', 6634),
 ('Boulder', 2542),
 ('Cambridge', 2433),
 ('Beaverton', 2252)]

In [15]:
df_a = df20[df20['city'] =='Austin']

In [19]:
df_a.to_csv("../austin20.csv", index = False)

In [16]:
df_a[(df_a.is_open==0)]

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
9,tXvdYGvlEceDljN8gt2_3Q,Capital City Barber Shop,"615 W Slaughter Ln, Ste 113",Austin,TX,78748,30.172706,-97.799920,4.0,5,0,"{'BusinessAcceptsCreditCards': 'False', 'Resta...","Barbers, Beauty & Spas","{'Monday': '9:0-17:0', 'Tuesday': '9:0-19:0', ..."
38,Xw8tuI30T-xihpzwBV-zJg,El Pollo Rey,1725 E Riverside Dr,Austin,TX,78741,30.243493,-97.730141,5.0,11,0,"{'RestaurantsGoodForGroups': 'True', 'Restaura...","Food Trucks, Restaurants, Specialty Food, Food...",None
65,z-0oY7VxQMQw3JHvdPejrA,Olmecas Mexican Restaurant,2121 E Oltorf St,Austin,TX,78741,30.230016,-97.732639,3.0,21,0,"{'Ambience': '{'romantic': False, 'intimate': ...","Coffee & Tea, Tex-Mex, Restaurants, Mexican, Food","{'Monday': '7:0-23:30', 'Tuesday': '7:0-23:30'..."
79,gjMCRTs0IZbw9bZLG837Bg,CaveMan Cuisine,,Austin,TX,78704,30.245673,-97.768836,1.5,6,0,"{'RestaurantsPriceRange2': '3', 'BusinessAccep...","Food, Food Delivery Services",None
108,qTdz29Nf3zoALiDDEKfWlw,Pho Oanh,"2121 E Oltorf St, Ste 12B",Austin,TX,78741,30.229913,-97.732649,3.5,15,0,"{'Ambience': '{'romantic': False, 'intimate': ...","Taiwanese, Vietnamese, Restaurants",None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160446,MAvCXmmGyWMNMPMVDZHqgg,A to Z Automotive,6200 N Lamar Blvd,Austin,TX,78752,30.330349,-97.723829,4.5,5,0,None,"Auto Repair, Automotive","{'Monday': '7:30-17:0', 'Tuesday': '7:30-17:0'..."
160453,VTpRbhxABeIAjkQcjTZqRQ,Smile Center Dental,"2501 W Parmer Ln, Ste 800",Austin,TX,78758,30.418014,-97.702276,3.5,10,0,"{'ByAppointmentOnly': 'True', 'BusinessAccepts...","General Dentistry, Health & Medical, Pediatric...","{'Monday': '11:0-19:0', 'Tuesday': '11:0-19:0'..."
160463,oRcudRswUuMXhoW42S7bcg,Paciugo Gelato,241 W 2nd St,Austin,TX,78701,30.264876,-97.746315,4.0,21,0,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Desserts, Food, Coffee & Tea","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'..."
160503,bsltkBbgcAUTaW3awpJpmg,Trai Mai Thai,603 W Live Oak,Austin,TX,78704,30.244371,-97.758238,3.0,6,0,"{'NoiseLevel': 'u'quiet'', 'RestaurantsTakeOut...","Thai, Restaurants, Vegetarian","{'Monday': '17:0-22:0', 'Tuesday': '17:0-22:0'..."
160505,C2rrd_YQjBt9WFVn6uwxLQ,Innu Hair Salon,2307 Hancock Dr,Austin,TX,78756,30.324526,-97.743677,4.0,30,0,"{'RestaurantsPriceRange2': '2', 'ByAppointment...","Beauty & Spas, Hair Salons","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."

In [8]:
df_l = df19[df19['city'] =='Las Vegas']

In [12]:
df_l.categories

6         Dry Cleaning & Laundry, Local Services, Laundr...
16                           Shopping, Shoe Stores, Fashion
36                          Mexican, Restaurants, Fast Food
42        Burgers, Restaurants, American (Traditional), ...
51                Hair Stylists, Hair Salons, Beauty & Spas
                                ...
209371    Commercial Real Estate, Mortgage Brokers, Home...
209372                                 Restaurants, Buffets
209375    Session Photography, Event Photography, Photog...
209382       Pets, Pet Sitting, Veterinarians, Pet Services
209386    Contractors, Local Services, Appliances & Repa...
Name: categories, Length: 31631, dtype: object

In [10]:
df_l[(df_l.is_open==0)]

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
16,uZuh51lXu7tsrC8RAwkg1A,Manolo Blahnik,3131 Las Vegas Blvd,Las Vegas,NV,89109,36.125732,-115.167608,4.5,32,0,"{'BusinessParking': '{'garage': True, 'street'...","Shopping, Shoe Stores, Fashion",None
36,fnZrZlqW1Z8iWgTVDfv_MA,Carl's Jr,9595 W Tropicana Ave,Las Vegas,NV,89147,36.099738,-115.301568,2.5,15,0,"{'Alcohol': 'u'none'', 'WiFi': 'u'no'', 'GoodF...","Mexican, Restaurants, Fast Food",None
42,fhNf_sg-XzZ3e7HEVGuOZg,Meat Chix And Wieners,6530 S Decatur Blvd,Las Vegas,NV,89118,36.071196,-115.207463,3.0,10,0,"{'RestaurantsPriceRange2': '2', 'BusinessParki...","Burgers, Restaurants, American (Traditional), ...","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'..."
68,bevuR6hYNuXCh9W0goe2kA,MD Laser Med Spa,"7175 W Lake Mead Blvd, Ste 168",Las Vegas,NV,89128,36.195266,-115.248140,3.5,33,0,"{'WheelchairAccessible': 'True', 'BusinessAcce...","Eyelash Service, Hair Salons, Skin Care, Docto...","{'Monday': '10:0-17:0', 'Tuesday': '10:0-17:0'..."
130,Q_dh08clYUPj13GmCRzIVA,Kulinarya Express Filipino Kitchen,"7960 S Rainbow Blvd, Ste 8000A",Las Vegas,NV,89139,36.043663,-115.241881,4.0,82,0,"{'BusinessParking': '{'garage': False, 'street...","Filipino, Restaurants, Breakfast & Brunch, Foo...","{'Monday': '0:0-0:0', 'Tuesday': '10:0-20:0', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209312,8yidA5O39XM4I1yvlTp2Fw,Patty's Closet,"7920 S Rainbow Blvd, Ste 115",Las Vegas,NV,89139,36.044718,-115.242705,4.5,52,0,"{'BusinessAcceptsCreditCards': 'True', 'BikePa...","Women's Clothing, Shopping, Fashion, Shoe Stores",None
209319,kGVAle6VpDvZHlEeTB2WhA,Deliria,"8480 S Las Vegas, Ste 110",Las Vegas,NV,89123,36.035739,-115.171471,4.0,10,0,"{'WiFi': 'u'no'', 'RestaurantsTakeOut': 'True'...","Delis, Restaurants, Sandwiches, Food, Pizza",None
209367,aJK0MWXKgXIgQUCM9fqSJQ,The Original Graziano's Pizza Restaurant,8410 W Desert Inn Rd,Las Vegas,NV,89117,36.129782,-115.274674,3.5,69,0,"{'BusinessParking': '{'garage': False, 'street...","Pizza, Italian, Restaurants","{'Monday': '11:0-21:30', 'Tuesday': '11:0-21:3..."
209369,5VXlHFrYZZzj7zfZEsz5nQ,Dragon Noodle Co.,3770 Las Vegas Blvd S,Las Vegas,NV,89109,36.105289,-115.174037,3.0,279,0,"{'RestaurantsTakeOut': 'True', 'BusinessAccept...","Chinese, Restaurants","{'Monday': '11:0-22:30', 'Tuesday': '11:0-22:3..."
209372,wjZ12shpUWAy4Boy0G5z1g,Island Buffet,"Tropicana Resort and Casino, 3801 Las Vegas Bl...",Las Vegas,NV,89109,36.099378,-115.171029,1.5,9,0,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Restaurants, Buffets",None

In [9]:
df_l.to_csv("vegas.csv", index = False)

In [7]:
Counter(df19.city).most_common(10)

[('Las Vegas', 31631),
 ('Toronto', 20366),
 ('Phoenix', 20171),
 ('Charlotte', 10422),
 ('Scottsdale', 9342),
 ('Calgary', 8377),
 ('Pittsburgh', 7630),
 ('Montr√©al', 6979),
 ('Mesa', 6577),
 ('Henderson', 5272)]

In [7]:
with open("../yelp_dataset/yelp_academic_dataset_checkin20.json", "r") as c20:
    checkin20 = pd.read_json(c20, orient="records", lines=True)

In [8]:
with open("../yelp_dataset/yelp_academic_dataset_checkin19.json", "r") as c19:
    checkin19 = pd.read_json(c19, orient="records", lines=True)

In [9]:
with open("../yelp_dataset/yelp_academic_dataset_checkin18.json", "r") as c18:
    checkin18 = pd.read_json(c18, orient="records", lines=True)

In [6]:
Counter(df21.city).most_common(10)

[('Philadelphia', 14569),
 ('Tucson', 9250),
 ('Tampa', 9050),
 ('Indianapolis', 7540),
 ('Nashville', 6971),
 ('New Orleans', 6209),
 ('Reno', 5935),
 ('Edmonton', 5054),
 ('Saint Louis', 4827),
 ('Santa Barbara', 3829)]

In [47]:
Counter(df20.city).most_common(10)

[('Austin', 22416),
 ('Portland', 18203),
 ('Vancouver', 13330),
 ('Atlanta', 12612),
 ('Orlando', 10637),
 ('Boston', 8263),
 ('Columbus', 6634),
 ('Boulder', 2542),
 ('Cambridge', 2433),
 ('Beaverton', 2252)]

In [50]:
Counter(df19.city).most_common()

[('Las Vegas', 31631),
 ('Toronto', 20366),
 ('Phoenix', 20171),
 ('Charlotte', 10422),
 ('Scottsdale', 9342),
 ('Calgary', 8377),
 ('Pittsburgh', 7630),
 ('Montr√©al', 6979),
 ('Mesa', 6577),
 ('Henderson', 5272)]

In [3]:
review_json_path = '../yelp_dataset/yelp_academic_dataset_review.json'

In [4]:
import numpy as np
import pandas as pd
b_pandas = []
r_dtypes = {"stars": np.float16, 
            "useful": np.int32, 
            "funny": np.int32,
            "cool": np.int32,
           }
with open(review_json_path, "r") as f:
    reader = pd.read_json(f, orient="records", lines=True, 
                          dtype=r_dtypes, chunksize=1000)
        
    for chunk in reader:
        reduced_chunk = chunk.drop(columns=['review_id', 'user_id'])\
                             .query("`date` >= '2016-12-01'")
        b_pandas.append(reduced_chunk)
    
b_pandas = pd.concat(b_pandas, ignore_index=True)

In [ ]:
b_pandas[b_pandas.date.dt.year==2022].business_id.nunique(

In [38]:
b_pandas[b_pandas.date.dt.year==2022].business_id.nunique()

19106

In [52]:
b_21 = b_pandas[b_pandas.date.dt.year==2021].business_id.unique()

In [55]:
b_20 = b_pandas[b_pandas.date.dt.year==2020].business_id.unique()

In [58]:
b_19 = b_pandas[b_pandas.date.dt.year==2019].business_id.unique()

In [61]:
len(set(b_20) & set(b_19) & set(b_21))

60559

In [62]:
len(set(b_20) & set(b_19))

75970

In [63]:
len(set(b_21) & set(b_20))

69850

In [64]:
len(set(b_21) & set(b_19))

71877

In [37]:
b_pandas[b_pandas.date.dt.year==2021].business_id.nunique()

87516

In [33]:
b_pandas[b_pandas.date.dt.year==2020].business_id.nunique()

89967

In [35]:
b_pandas[b_pandas.date.dt.year==2019].business_id.nunique()

101959

In [28]:
b_pandas[b_pandas.date.dt.year==2018].business_id.nunique()

100944

In [36]:
b_pandas[b_pandas.date.dt.year==2017].business_id.nunique()

96507

In [11]:
Counter(df20.city).most_common(10)

[('Austin', 22416),
 ('Portland', 18203),
 ('Vancouver', 13330),
 ('Atlanta', 12612),
 ('Orlando', 10637),
 ('Boston', 8263),
 ('Columbus', 6634),
 ('Boulder', 2542),
 ('Cambridge', 2433),
 ('Beaverton', 2252)]

In [23]:
df20[df20['postal_code']=='11746']

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
114018,kSR97n4KI5aAq-zICREdcw,Sugar N Spice Patisserie,,Austin,TX,11746,30.267153,-97.743061,2.0,9,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Bakeries, Food, Cupcakes, Specialty Food, Maca...",None

In [24]:
df20[df20['city']=='Austin']

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
8,N3_Gs3DnX4k9SgpwJxdEfw,Lane Wells Jewelry Repair,"7801 N Lamar Blvd, Ste A140",Austin,TX,78752,30.346169,-97.711458,5.0,30,1,"{'RestaurantsPriceRange2': '1', 'ByAppointment...","Shopping, Jewelry Repair, Appraisal Services, ...","{'Monday': '12:15-17:0', 'Tuesday': '12:15-17:..."
9,tXvdYGvlEceDljN8gt2_3Q,Capital City Barber Shop,"615 W Slaughter Ln, Ste 113",Austin,TX,78748,30.172706,-97.799920,4.0,5,0,"{'BusinessAcceptsCreditCards': 'False', 'Resta...","Barbers, Beauty & Spas","{'Monday': '9:0-17:0', 'Tuesday': '9:0-19:0', ..."
24,nTIhpR7MhsALPwg_Hh14EA,DoubleTree by Hilton Hotel Austin,6505 N Interstate 35,Austin,TX,78752,30.326377,-97.704543,3.0,139,1,"{'WiFi': 'u'free'', 'RestaurantsPriceRange2': ...","Hotels, Hotels & Travel, Event Planning & Serv...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
27,8XyEpVdAO0o6iVkVxkWosQ,PS Property Management Company,"2506 S Lamar Blvd, Ste 2",Austin,TX,78704,30.246465,-97.778738,4.5,9,1,{'BusinessAcceptsCreditCards': 'True'},"Home Services, Real Estate, Property Management","{'Monday': '9:0-17:0', 'Tuesday': '9:0-17:0', ..."
37,NVfOn7TdnHbaGH97CVB_Qg,McKinley Chiropractic,"5625 Eiger Rd, Ste 160",Austin,TX,78735,30.244902,-97.857409,5.0,5,1,"{'BusinessAcceptsCreditCards': 'True', 'Accept...","Chiropractors, Health & Medical","{'Monday': '9:0-17:45', 'Tuesday': '12:0-17:45..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160564,3hST-OFbQzCgte1XugEtug,AcuStretch,13018 N Hwy 183,Austin,TX,78750,30.437784,-97.777968,4.0,7,1,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Massage, Beauty & Spas","{'Monday': '10:0-21:0', 'Tuesday': '10:0-21:0'..."
160566,N1rn9F8Xj8zQRfVrrQHgnw,Salute Oral & Facial Surgery,"10801 N Mo Pac Expy, Ste 2-130",Austin,TX,78759,30.398422,-97.730128,3.5,13,1,"{'ByAppointmentOnly': 'True', 'BusinessAccepts...","Health & Medical, General Dentistry, Dentists","{'Monday': '8:0-17:0', 'Tuesday': '8:0-17:0', ..."
160567,TLg7py9H1W0E-F8BAn5OJQ,Austin Stained Concrete and More,5710 Fitchwood Ln,Austin,TX,78749,30.210815,-97.869660,5.0,19,1,{'BusinessAcceptsCreditCards': 'True'},"Masonry/Concrete, Home Services, Flooring","{'Monday': '8:0-17:0', 'Tuesday': '8:0-17:0', ..."
160577,m1Qw53OgkxrWu59oddVf9A,Capital Area Speech & Occupational Therapy,"12710 Research Blvd, Ste 395",Austin,TX,78759,30.431920,-97.765740,4.0,16,1,"{'ByAppointmentOnly': 'True', 'AcceptsInsuranc...","Educational Services, Health & Medical, Occupa...","{'Monday': '8:30-18:30', 'Tuesday': '8:30-18:3..."
160580,D2mHoIDXx9N8mS1pGoKV9Q,Eleven Oaks Realty,,Austin,TX,78701,30.272921,-97.744386,4.0,8,1,None,"Real Estate, Real Estate Services, Home Servic...","{'Monday': '9:0-19:0', 'Tuesday': '9:0-19:0', ..."

In [21]:
Counter(df20[df20['city']=='Austin'].postal_code).most_common()

[('78704', 2082),
 ('78701', 1788),
 ('78745', 1353),
 ('78759', 1345),
 ('78758', 1291),
 ('78702', 1067),
 ('78757', 997),
 ('78705', 978),
 ('78746', 974),
 ('78753', 820),
 ('78748', 782),
 ('78731', 625),
 ('78703', 597),
 ('78756', 580),
 ('78751', 575),
 ('78741', 495),
 ('78752', 491),
 ('78723', 441),
 ('78749', 420),
 ('78750', 395),
 ('78735', 392),
 ('78727', 360),
 ('78744', 344),
 ('78734', 282),
 ('78729', 251),
 ('78738', 234),
 ('78728', 234),
 ('78754', 200),
 ('78737', 184),
 ('78722', 181),
 ('78726', 179),
 ('78732', 176),
 ('78730', 141),
 ('78736', 139),
 ('78719', 117),
 ('78724', 105),
 ('78721', 100),
 ('78747', 96),
 ('73301', 86),
 ('78798', 65),
 ('78739', 49),
 ('78733', 48),
 ('78712', 46),
 ('78742', 21),
 ('78617', 20),
 ('78725', 19),
 ('78799', 19),
 ('78715', 18),
 ('78720', 17),
 ('', 14),
 ('78709', 13),
 ('78755', 13),
 ('78766', 12),
 ('78767', 10),
 ('78716', 10),
 ('78652', 9),
 ('78717', 8),
 ('78708', 7),
 ('78765', 7),
 ('78610', 7),
 ('78761', 7),
 ('78760', 6),
 ('78660', 6),
 ('78713', 6),
 ('78768', 5),
 ('78681', 4),
 ('78714', 4),
 ('78762', 4),
 ('78710', 4),
 ('78665', 2),
 ('78653', 2),
 ('78641', 2),
 ('78764', 2),
 ('78718', 2),
 ('78640', 2),
 ('78711', 2),
 ('78763', 2),
 ('78669', 1),
 ('78680', 1),
 ('78792', 1),
 ('78773', 1),
 ('78664', 1),
 ('78378', 1),
 ('75749', 1),
 ('78646', 1),
 ('78774', 1),
 ('75783', 1),
 ('78613', 1),
 ('60015', 1),
 ('79748', 1),
 ('78707', 1),
 ('55912', 1),
 ('77401', 1),
 ('78478', 1),
 ('78778', 1),
 ('76530', 1),
 ('23000', 1),
 ('11746', 1),
 ('75745', 1),
 ('78620', 1),
 ('73751', 1),
 ('78017', 1)]

In [12]:
Counter(df20.state).most_common(10)

[('MA', 36012),
 ('OR', 25175),
 ('TX', 24485),
 ('FL', 21907),
 ('GA', 18090),
 ('BC', 17298),
 ('OH', 11258),
 ('CO', 3198),
 ('WA', 3121),
 ('CA', 13)]

In [13]:
Counter(df20.state).most_common()

[('AZ', 60803),
 ('NV', 39084),
 ('ON', 36627),
 ('OH', 16392),
 ('NC', 16218),
 ('PA', 12376),
 ('QC', 10233),
 ('AB', 8682),
 ('WI', 5525),
 ('IL', 2034),
 ('SC', 1328),
 ('CA', 23),
 ('NY', 22),
 ('TX', 6),
 ('WA', 5),
 ('GA', 3),
 ('AL', 3),
 ('FL', 3),
 ('CO', 2),
 ('BC', 2),
 ('UT', 2),
 ('VT', 2),
 ('NE', 2),
 ('MI', 2),
 ('CT', 2),
 ('XWY', 1),
 ('YT', 1),
 ('HPL', 1),
 ('DOW', 1),
 ('AR', 1),
 ('HI', 1),
 ('MB', 1),
 ('OR', 1),
 ('AK', 1),
 ('VA', 1),
 ('MO', 1),
 ('DUR', 1)]

In [33]:
df20[(df20.city=='Phoenix')&(df20.categories.str.contains('Restaurants'))&(df20.is_open==1)].sort_values(by='review_count', ascending=False)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
207685,utIA0LyQmwP-9DRyxUe6qQ,"Snooze, An A.M. Eatery","2045 E Camelback Rd, Ste A17",Phoenix,AZ,85016,33.508204,-112.037033,4.0,3515,1,"{'RestaurantsPriceRange2': '2', 'RestaurantsGo...","Breakfast & Brunch, Coffee & Tea, Sandwiches, ...","{'Monday': '6:30-14:30', 'Tuesday': '6:30-14:3..."
171190,VyVIneSU7XAWgMBllI6LnQ,Bobby Q,8501 N 27th Ave,Phoenix,AZ,85051,33.561085,-112.115747,4.5,3302,1,"{'WiFi': 'u'free'', 'RestaurantsPriceRange2': ...","Barbeque, Caterers, Event Planning & Services,...","{'Monday': '11:0-21:0', 'Tuesday': '11:0-22:0'..."
151899,pSQFynH1VxkfSmehRXlZWw,Pizzeria Bianco,623 E Adams St,Phoenix,AZ,85004,33.449160,-112.065635,4.0,2527,1,"{'Alcohol': ''beer_and_wine'', 'BusinessAccept...","Sandwiches, Tapas/Small Plates, Restaurants, S...","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
10824,yNPh5SO-7wr8HPpVCDPbXQ,The Arrogant Butcher,"2 E Jefferson St, Ste 150",Phoenix,AZ,85004,33.447392,-112.072831,4.0,2358,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","American (New), Gastropubs, Seafood, American ...","{'Monday': '11:0-16:0', 'Tuesday': '11:0-16:0'..."
141155,Xg5qEQiB-7L6kGJ5F4K3bQ,Little Miss BBQ,4301 E University Dr,Phoenix,AZ,85034,33.421714,-111.989161,5.0,2329,1,"{'RestaurantsDelivery': 'False', 'RestaurantsA...","Barbeque, Restaurants","{'Monday': '0:0-0:0', 'Tuesday': '11:0-16:0', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186884,LQblku8iteGm5YFa60c7xA,Dairy Queen Grill & Chill,"Desert Sky Mall, Ste G008",Phoenix,AZ,85033,33.476402,-112.225538,4.0,3,1,"{'RestaurantsGoodForGroups': 'True', 'Restaura...","Fast Food, Food, Restaurants, Ice Cream & Froz...","{'Monday': '10:0-21:0', 'Tuesday': '10:0-21:0'..."
125489,5gKonbvyRxrC40Tc6mjfrA,Taqueria La Condesa,3001 E Washington St,Phoenix,AZ,85034,33.447871,-112.016545,5.0,3,1,"{'HasTV': 'True', 'Ambience': '{'touristy': Fa...","Restaurants, Mexican, Automotive, Gas Stations","{'Monday': '6:30-20:30', 'Tuesday': '6:30-20:3..."
124769,WZAENeqQHGRIjSD7VTAmyQ,Diamond Plate Restaurant,1820 S 7th St,Phoenix,AZ,85034,33.429983,-112.066472,1.5,3,1,"{'Caters': 'False', 'GoodForKids': 'False', 'N...","Chicken Wings, Restaurants, American (Traditio...","{'Monday': '5:30-0:0', 'Tuesday': '5:30-0:0', ..."
93324,_50O0IFRHOLwl2DC9Q1U2g,Let It Snow Cones,"4747 E Elliott Rd, Ste 34",Phoenix,AZ,85044,33.347971,-111.982151,5.0,3,1,"{'WheelchairAccessible': 'True', 'BikeParking'...","Shaved Ice, Restaurants, Food Trucks, Ice Crea...","{'Monday': '0:0-0:0', 'Wednesday': '13:0-20:0'..."
174404,A6qLlVs7kR8fxlZmQ_Zecw,Metro Cafe,"10000 N 31st Ave, Ste A106",Phoenix,AZ,85051,33.577240,-112.127022,3.5,3,1,"{'HasTV': 'True', 'Ambience': '{'touristy': Fa...","Mexican, Wraps, Breakfast & Brunch, Sandwiches...",None

In [34]:
df[(df.city=='Phoenix')&(df.categories.str.contains('Restaurants'))&(df.is_open==1)].sort_values(by='review_count', ascending=False)

Empty DataFrame
Columns: [business_id, name, address, city, state, postal_code, latitude, longitude, stars, review_count, is_open, attributes, categories, hours]
Index: []

In [41]:
import pyreadstat

In [38]:
Counter(df20.city).most_common()[:10]

[('Las Vegas', 31631),
 ('Toronto', 20366),
 ('Phoenix', 20171),
 ('Charlotte', 10422),
 ('Scottsdale', 9342),
 ('Calgary', 8377),
 ('Pittsburgh', 7630),
 ('Montr√©al', 6979),
 ('Mesa', 6577),
 ('Henderson', 5272)]

In [39]:
Counter(df.city).most_common()[:10]

[('Philadelphia', 14569),
 ('Tucson', 9250),
 ('Tampa', 9050),
 ('Indianapolis', 7540),
 ('Nashville', 6971),
 ('New Orleans', 6209),
 ('Reno', 5935),
 ('Edmonton', 5054),
 ('Saint Louis', 4827),
 ('Santa Barbara', 3829)]

In [30]:
df20[(df20.state=='AZ')&(df20.categories.str.contains('Restaurants'))&(df20.is_open==1)]

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
33,vjTVxnsQEZ34XjYNS-XUpA,Wetzel's Pretzels,"4550 East Cactus Rd, #KSFC-4",Phoenix,AZ,85032,33.602822,-111.983533,4.0,10,1,"{'GoodForKids': 'True', 'RestaurantsTakeOut': ...","Food, Pretzels, Bakeries, Fast Food, Restaurants","{'Monday': '10:0-21:0', 'Tuesday': '10:0-21:0'..."
59,LAoSegVNU4wx4GTA8reB6A,Tzikii Food Truck,7510 S Priest Dr,Tempe,AZ,85283,33.350104,-111.963660,3.0,4,1,"{'RestaurantsTakeOut': 'False', 'WheelchairAcc...","Restaurants, Egyptian, Food Trucks, Food, Midd...",None
89,j9bWpCRwpDVfwVT_V85qeA,Papaya Thai,2706 E University Dr,Mesa,AZ,85213,33.423705,-111.772890,2.5,130,1,"{'Caters': 'False', 'OutdoorSeating': 'False',...","Food, Ethnic Food, Specialty Food, Restaurants...","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
107,W7hCuNdn2gzehta6eSHzgQ,Pete's Fish & Chips,1017 E Apache Blvd,Tempe,AZ,85281,33.414507,-111.923721,2.0,117,1,"{'NoiseLevel': 'u'average'', 'BusinessAcceptsC...","Restaurants, Fish & Chips, Seafood","{'Monday': '10:30-22:0', 'Tuesday': '10:30-22:..."
108,8nP8ghEpT6WFcM6tfqAaGA,Sugar Bowl,4005 N Scottsdale Rd,Scottsdale,AZ,85251,33.493775,-111.925933,3.5,720,1,"{'RestaurantsAttire': ''casual'', 'Alcohol': '...","Ice Cream & Frozen Yogurt, Sandwiches, Food, A...","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209341,EDa7_YfEB2HDOyxDMbipQA,Barro's Pizza,15475 W Mcdowell Rd,Goodyear,AZ,85338,33.462607,-112.391739,3.5,157,1,"{'RestaurantsDelivery': 'True', 'HasTV': 'True...","Italian, Sandwiches, Pizza, Restaurants","{'Monday': '0:0-0:0', 'Tuesday': '10:30-21:0',..."
209358,_bvc2j6E8mk_ZiMoh2iMuQ,Sonic Drive-In,6501 W Glendale Ave,Glendale,AZ,85301,33.537861,-112.199338,2.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Alcoho...","Ice Cream & Frozen Yogurt, Burgers, Restaurant...","{'Monday': '0:0-0:0', 'Tuesday': '6:0-22:0', '..."
209376,cmsAFAymfVoBitSF8R6GKw,Yao Fine Chinese Cuisine,"2487 S Gilbert Rd, Ste 102",Gilbert,AZ,85295,33.304935,-111.788861,4.0,230,1,"{'RestaurantsGoodForGroups': 'True', 'Ambience...","Chinese, Restaurants","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
209380,YZeUH6zYS0dq5QHLYZhUnQ,Hooters,2820 N 75th Ave,Phoenix,AZ,85035,33.479139,-112.221142,2.0,106,1,"{'NoiseLevel': ''very_loud'', 'WiFi': ''no'', ...","Nightlife, American (Traditional), Chicken Win...",None
209390,SYa2j1boLF8DcGVOYfHPcA,Five Guys,7014-590 E Camelback Rd,Scottsdale,AZ,85251,33.504062,-111.929431,3.5,97,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","American (New), Food, Burgers, Restaurants, Fa...","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'..."

In [19]:
df20[df20.is_open==1]

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,f9NumwFMBDn751xgFiRbNA,The Range At Lake Norman,10913 Bailey Rd,Cornelius,NC,28031,35.462724,-80.852612,3.5,36,1,"{'BusinessAcceptsCreditCards': 'True', 'BikePa...","Active Life, Gun/Rifle Ranges, Guns & Ammo, Sh...","{'Monday': '10:0-18:0', 'Tuesday': '11:0-20:0'..."
1,Yzvjg0SayhoZgCljUJRF9Q,"Carlos Santo, NMD","8880 E Via Linda, Ste 107",Scottsdale,AZ,85258,33.569404,-111.890264,5.0,4,1,"{'GoodForKids': 'True', 'ByAppointmentOnly': '...","Health & Medical, Fitness & Instruction, Yoga,...",None
2,XNoUzKckATkOD1hP6vghZg,Felinus,3554 Rue Notre-Dame O,Montreal,QC,H4C 1P4,45.479984,-73.580070,5.0,5,1,None,"Pets, Pet Services, Pet Groomers",None
4,51M2Kk903DFYI6gnB5I6SQ,USE MY GUY SERVICES LLC,4827 E Downing Cir,Mesa,AZ,85205,33.428065,-111.726648,4.5,26,1,"{'BusinessAcceptsCreditCards': 'True', 'ByAppo...","Home Services, Plumbing, Electricians, Handyma...","{'Monday': '0:0-0:0', 'Tuesday': '9:0-16:0', '..."
5,cKyLV5oWZJ2NudWgqs8VZw,Oasis Auto Center - Gilbert,"1720 W Elliot Rd, Ste 105",Gilbert,AZ,85233,33.350399,-111.827142,4.5,38,1,{'BusinessAcceptsCreditCards': 'True'},"Auto Repair, Automotive, Oil Change Stations, ...","{'Monday': '7:0-18:0', 'Tuesday': '7:0-18:0', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209386,JjcJVqhZXhP4tvOhg3fnag,Water Heater Pros,,Las Vegas,NV,89120,36.076977,-115.244794,5.0,217,1,"{'BusinessAcceptsCreditCards': 'True', 'ByAppo...","Contractors, Local Services, Appliances & Repa...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-17:0', '..."
209387,KdGtDThLduB8Vf-z-qKEFA,Aldo,6455 Macleod Trl SW,Calgary,AB,T2H,50.997571,-114.073369,3.5,3,1,None,"Shopping, Fashion, Accessories, Shoe Stores",None
209390,SYa2j1boLF8DcGVOYfHPcA,Five Guys,7014-590 E Camelback Rd,Scottsdale,AZ,85251,33.504062,-111.929431,3.5,97,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","American (New), Food, Burgers, Restaurants, Fa...","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'..."
209391,RSSIsgO00OuWQTRoITacpA,Indian Trail Dog Training,,Indian Trail,NC,28079,35.101965,-80.599385,5.0,3,1,None,"Pet Services, Pet Training, Pets","{'Monday': '0:0-0:0', 'Tuesday': '7:0-19:0', '..."
209392,tOcYmewXFhQeZh3V42ymwg,Kudlow Ye,"21 St Clair Avenue E, Suite 401",Toronto,ON,M4T 1L9,43.688214,-79.392756,5.0,3,1,None,"Tax Services, Professional Services, Accountan...","{'Monday': '9:0-18:0', 'Tuesday': '9:0-18:0', ..."

In [3]:
Counter(df.state).most_common()

[('PA', 34039),
 ('FL', 26330),
 ('TN', 12056),
 ('IN', 11247),
 ('MO', 10913),
 ('LA', 9924),
 ('AZ', 9912),
 ('NJ', 8536),
 ('NV', 7715),
 ('AB', 5573),
 ('CA', 5203),
 ('ID', 4467),
 ('DE', 2265),
 ('IL', 2145),
 ('TX', 4),
 ('CO', 3),
 ('WA', 2),
 ('HI', 2),
 ('MA', 2),
 ('NC', 1),
 ('UT', 1),
 ('MT', 1),
 ('MI', 1),
 ('SD', 1),
 ('XMS', 1),
 ('VI', 1),
 ('VT', 1)]

In [24]:
df[df.postal_code=='']

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
853,6cPVGUOVlHa6TwlgU08IXQ,Dr.Green,,Edmonton,AB,,53.544389,-113.490927,1.5,7,1,None,"Landscaping, Professional Services, Home Services",None
2617,siwG4ZM7RjUDO52DI84m3w,Ray's Vegan Soul,,St. Petersburg,FL,,27.767601,-82.640292,5.0,5,1,{'RestaurantsTakeOut': 'True'},"Soul Food, Vegan, Event Planning & Services, R...",None
2984,m84BCUA6aDi03mRyufHYBw,Harlow Pest & Sanitation Control,,Edmonton,AB,,53.546124,-113.493823,2.5,6,1,None,"Pest Control, Wildlife Control, Local Services","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
11334,VEdEuOfDGhgRWO-PipfB7w,Fill A Seat Philadelphia,,Philadelphia,PA,,39.952335,-75.163789,3.0,6,0,{'GoodForKids': 'False'},Arts & Entertainment,None
16507,--sXnWH9Xm6_NvIjyuA99w,Philadelphia,,Philadelphia,PA,,39.952584,-75.165222,4.0,29,1,{'GoodForKids': 'True'},"Public Services & Government, Local Flavor",None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141819,81ayGRiiiGMNVv5xQgFK2A,National Bartenders,,Philadelphia,PA,,39.952584,-75.165222,1.5,6,0,{'BusinessAcceptsCreditCards': 'True'},"Event Planning & Services, Bartenders","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
143722,_E7p_2LZk7cat6mnIx2A8g,The Biggest Little Fashion Truck,,Reno,NV,,39.529633,-119.813803,4.5,6,1,None,"Shopping, Women's Clothing, Fashion",None
143725,ezLDUMrSdXBCk6QOqOrPwA,Adult Swim,,Indianapolis,IN,,39.811099,-86.159835,4.0,9,1,{'GoodForKids': 'False'},Local Flavor,None
148627,RzKHpILaR1nAKDHeKxVY8A,Wanderlust Pizza,,Saint Louis,MO,,38.649590,-90.225220,4.0,19,0,"{'HasTV': 'False', 'Ambience': '{'romantic': F...","Restaurants, Street Vendors, Food, Food Trucks...","{'Monday': '11:0-13:30', 'Tuesday': '11:0-13:3..."
149513,eTg443zUsuwc1u63RKtXWg,Gateway Dog House,,Saint Louis,MO,,38.627003,-90.199404,4.0,7,0,"{'GoodForKids': 'True', 'NoiseLevel': 'u'avera...","Barbeque, Food, Street Vendors, Hot Dogs, Rest...","{'Monday': '8:0-13:30', 'Tuesday': '8:0-13:30'..."

In [18]:
Counter(df20.city).most_common()

[('Las Vegas', 31631),
 ('Toronto', 20366),
 ('Phoenix', 20171),
 ('Charlotte', 10422),
 ('Scottsdale', 9342),
 ('Calgary', 8377),
 ('Pittsburgh', 7630),
 ('Montr√©al', 6979),
 ('Mesa', 6577),
 ('Henderson', 5272),
 ('Tempe', 4797),
 ('Chandler', 4580),
 ('Cleveland', 3857),
 ('Glendale', 3824),
 ('Gilbert', 3745),
 ('Madison', 3685),
 ('Mississauga', 3518),
 ('Peoria', 2080),
 ('Markham', 1963),
 ('North Las Vegas', 1677),
 ('Champaign', 1327),
 ('North York', 1319),
 ('Scarborough', 1244),
 ('Surprise', 1218),
 ('Richmond Hill', 1153),
 ('Brampton', 1146),
 ('Concord', 1125),
 ('Vaughan', 1045),
 ('Goodyear', 951),
 ('Etobicoke', 841),
 ('Matthews', 812),
 ('Avondale', 745),
 ('Fort Mill', 696),
 ('Huntersville', 684),
 ('Gastonia', 564),
 ('Lakewood', 562),
 ('Mentor', 559),
 ('Akron', 512),
 ('Cornelius', 495),
 ('Laval', 472),
 ('Westlake', 444),
 ('Monroeville', 442),
 ('Thornhill', 434),
 ('North Olmsted', 428),
 ('Strongsville', 426),
 ('Urbana', 425),
 ('Cave Creek', 424),
 ('Aurora', 421),
 ('Newmarket', 411),
 ('Medina', 409),
 ('Oakville', 401),
 ('Cuyahoga Falls', 401),
 ('Middleton', 392),
 ('Pineville', 382),
 ('Pickering', 371),
 ('Fountain Hills', 369),
 ('Rock Hill', 346),
 ('Ajax', 343),
 ('Parma', 341),
 ('Beachwood', 328),
 ('Whitby', 323),
 ('Indian Trail', 313),
 ('Wexford', 302),
 ('Sun City', 300),
 ('Boulder City', 283),
 ('Sun Prairie', 276),
 ('Willoughby', 274),
 ('Kent', 268),
 ('Woodbridge', 264),
 ('Avon', 262),
 ('Rocky River', 261),
 ('Elyria', 256),
 ('Litchfield Park', 251),
 ('Stow', 246),
 ('Solon', 237),
 ('Bethel Park', 236),
 ('Cleveland Heights', 228),
 ('Verona', 221),
 ('Chagrin Falls', 220),
 ('Hudson', 213),
 ('Brossard', 209),
 ('Fitchburg', 206),
 ('Monroe', 203),
 ('Brunswick', 199),
 ('Bridgeville', 199),
 ('Coraopolis', 195),
 ('Canonsburg', 189),
 ('Waxhaw', 188),
 ('Belmont', 187),
 ('Airdrie', 186),
 ('Montreal', 180),
 ('Mayfield Heights', 180),
 ('Verdun', 174),
 ('Fairlawn', 173),
 ('North Royalton', 170),
 ('Tolleson', 168),
 ('East York', 166),
 ('Middleburg Heights', 166),
 ('West Mifflin', 160),
 ('Painesville', 157),
 ('Saint-Laurent', 156),
 ('Monona', 155),
 ('Streetsboro', 153),
 ('Harrisburg', 151),
 ('Twinsburg', 148),
 ('Independence', 148),
 ('Berea', 147),
 ('Broadview Heights', 142),
 ('Paradise Valley', 141),
 ('Denver', 140),
 ('Laveen', 135),
 ('El Mirage', 135),
 ('Homestead', 132),
 ('Lyndhurst', 130),
 ('Lorain', 129),
 ('Avon Lake', 128),
 ('Dorval', 126),
 ('Sewickley', 126),
 ('Gibsonia', 125),
 ('Carnegie', 124),
 ('Stoughton', 122),
 ('York', 122),
 ('Amherst', 122),
 ('Murrysville', 121),
 ('Bedford', 120),
 ('Kannapolis', 120),
 ('North Ridgeville', 120),
 ('Mint Hill', 119),
 ('Macedonia', 119),
 ('Fairview Park', 118),
 ('Euclid', 117),
 ('Davidson', 115),
 ('Pointe-Claire', 115),
 ('Northfield', 114),
 ('Sun City West', 114),
 ('Westmount', 112),
 ('Carefree', 112),
 ('McMurray', 109),
 ('Waunakee', 108),
 ('Dollard-des-Ormeaux', 107),
 ('Allison Park', 107),
 ('Indian Land', 106),
 ('Chardon', 103),
 ('Queen Creek', 98),
 ('Brecksville', 95),
 ('South Euclid', 93),
 ('Lasalle', 92),
 ('Longueuil', 91),
 ('Brooklyn', 87),
 ('New Kensington', 87),
 ('Buckeye', 86),
 ('Eastlake', 86),
 ('Shaker Heights', 85),
 ('Parma Heights', 84),
 ('Irwin', 83),
 ('Savoy', 83),
 ('Oregon', 81),
 ('Wickliffe', 81),
 ('Willowick', 78),
 ('Stouffville', 76),
 ('Chesterland', 76),
 ('Vaudreuil-Dorion', 76),
 ('Youngtown', 71),
 ('North Versailles', 69),
 ('Maple', 67),
 ('Glenshaw', 67),
 ('McKees Rocks', 66),
 ('Woodmere', 66),
 ('Brook Park', 66),
 ('McKeesport', 65),
 ('Oakmont', 65),
 ('Tallmadge', 65),
 ('Lake Wylie', 62),
 ('Mount Horeb', 61),
 ('Olmsted Falls', 59),
 ('Pierrefonds', 57),
 ('Moon Township', 57),
 ('Unionville', 57),
 ('Garfield Heights', 56),
 ('Whitchurch-Stouffville', 56),
 ('Lachine', 56),
 ('Clover', 56),
 ('Oakdale', 56),
 ('Warrensville Heights', 55),
 ('Maple Heights', 55),
 ('Rantoul', 55),
 ('Mount Holly', 55),
 ('Saint-Sauveur', 55),
 ('Tarentum', 55),
 ('Bolton', 55),
 ('Willoughby Hills', 53),
 ('Bay Village', 52),
 ('Kirkland', 51),
 ('Mooresville', 51),
 ('Richfield', 50),
 ('University Heights', 47),
 ('Cottage Grove', 46),
 ('North Huntingdon', 46),
 ('Bellevue', 46),
 ('Copley', 45),
 ('Mahomet', 45),
 ('White Oak', 44),
 ('Highland Heights', 42),
 ('Ambridge', 42),
 ('Boucherville', 41),
 ('Georgetown', 40),
 ('Mc Kees Rocks', 40),
 ('Outremont', 39),
 ('Elizabeth', 39),
 ('Pleasant Hills', 39),
 ('Sun Lakes', 39),
 ('Seven Hills', 38),
 ('Halton Hills', 38),
 ('Mont-Royal', 38),
 ('Tega Cay', 38),
 ('Chestermere', 37),
 ('Saint-Leonard', 36),
 ('Bradford', 36),
 ('Monticello', 36),
 ('Bedford Heights', 36),
 ('Penn Hills', 36),
 ('Saint-Jean-sur-Richelieu', 35),
 ('Caledon', 35),
 ('Anthem', 34),
 ('Sheffield Village', 34),
 ('Dallas', 33),
 ('Cheswick', 33),
 ('Middlefield', 33),
 ('McFarland', 33),
 ('De Forest', 31),
 ('Munhall', 31),
 ('Dollard-Des-Ormeaux', 30),
 ('Apache Junction', 30),
 ('Burton', 30),
 ('Wadsworth', 30),
 ('Cross Plains', 29),
 ('Columbia Station', 29),
 ('Valley View', 29),
 ('Mc Farland', 28),
 ('N Las Vegas', 28),
 ('Richmond Heights', 28),
 ('Peninsula', 28),
 ('Guadalupe', 28),
 ('Saint-Hubert', 28),
 ('Greenfield Park', 27),
 ('Saint-Lambert', 27),
 ('East Gwillimbury', 27),
 ('Aspinwall', 26),
 ('King City', 26),
 ('Terrebonne', 26),
 ('Pepper Pike', 25),
 ('Midland', 25),
 ('Finleyville', 25),
 ('LaSalle', 25),
 ('Stanley', 24),
 ('Imperial', 24),
 ('Lower Burrell', 24),
 ('Hinckley', 23),
 ('Brentwood', 23),
 ('Rosem√®re', 23),
 ('Saint-Eustache', 23),
 ('Wesley Chapel', 23),
 ('Plum', 22),
 ('Anjou', 22),
 ('Rocky View', 22),
 ('Grafton', 22),
 ('Higley', 22),
 ('West Homestead', 22),
 ('Stallings', 22),
 ('Newbury', 21),
 ('DeForest', 21),
 ('La Prairie', 21),
 ('Clairton', 21),
 ('Springdale', 21),
 ('Millvale', 21),
 ('Turtle Creek', 21),
 ('Castle Shannon', 20),
 ('Windsor', 20),
 ('Robinson Township', 20),
 ('Saint-J√©r√¥me', 20),
 ('Monongahela', 20),
 ('Mantua', 19),
 ('Saint Joseph', 19),
 ('Sainte-Anne-de-Bellevue', 19),
 ('Kirtland', 19),
 ('Mckees Rocks', 19),
 ('Ravenna', 19),
 ('Paradise', 19),
 ('Lowell', 19),
 ('Bradford West Gwillimbury', 19),
 ('Munroe Falls', 18),
 ('Ch√¢teauguay', 18),
 ('Mount Lebanon', 18),
 ('Sheffield Lake', 18),
 ('Blainville', 18),
 ('Waddell', 18),
 ('Boisbriand', 17),
 ('Valley City', 17),
 ('Sainte-Julie', 17),
 ('Las vegas', 17),
 ('Laveen Village', 16),
 ('Orange', 16),
 ('Belleville', 16),
 ('South Park', 16),
 ('Mayfield', 16),
 ('Moon', 16),
 ('Trafford', 16),
 ('Weddington', 16),
 ('Milton', 15),
 ('North Randall', 15),
 ('Cramerton', 15),
 ('West View', 15),
 ('Orange Village', 15),
 ('Locust', 15),
 ('Brookpark', 15),
 ('Chambly', 14),
 ('phoenix', 14),
 ('Ahwatukee', 14),
 ('Rocky View County', 14),
 ('Etna', 14),
 ('Jefferson Hills', 14),
 ('Nellis AFB', 14),
 ('Oakwood Village', 14),
 ('Braddock', 13),
 ('Sainte-Th√©r√®se', 13),
 ('LAS VEGAS', 13),
 ('Hampton Township', 13),
 ('Mc Murray', 13),
 ('Leetsdale', 13),
 ('Saint-L√©onard', 13),
 ('Heidelberg', 12),
 ('Champlain', 12),
 ('Crafton', 12),
 ('Mcmurray', 12),
 ('McDonald', 12),
 ('Saint-Hyacinthe', 12),
 ('Upper Saint Clair', 12),
 ('Uxbridge', 12),
 ('Summerlin', 12),
 ('Avalon', 11),
 ('Blue Diamond', 11),
 ('Swissvale', 11),
 ('Wilmerding', 11),
 ('Mentor-on-the-Lake', 11),
 ('Fort McDowell', 11),
 ('Beloeil', 11),
 ('Mont-Saint-Hilaire', 11),
 ('Saint-Jerome', 11),
 ('Wilkinsburg', 11),
 ('Beaconsfield', 11),
 ('Norton', 11),
 ('Cecil', 11),
 ('Balzac', 11),
 ('Robinson', 11),
 ('Black Earth', 10),
 ('Montreal-Nord', 10),
 ('Brooklin', 10),
 ('Sainte-Ad√®le', 10),
 ('Sainte-Adele', 10),
 ('Caledon East', 10),
 ('Repentigny', 10),
 ('Moreland Hills', 10),
 ('South Park Township', 10),
 ('Deforest', 10),
 ('Sharpsburg', 10),
 ('Mayfield Village', 10),
 ('Sheffield', 10),
 ('Dravosburg', 10),
 ("L'√éle-Perrot", 10),
 ('N. Las Vegas', 10),
 ('Mt Lebanon', 10),
 ('Litchfield', 10),
 ('Schomberg', 10),
 ('Spring Valley', 10),
 ('Pittsburg', 9),
 ('Dormont', 9),
 ('Middleburg Hts', 9),
 ('MESA', 9),
 ('Saint-Bruno-de-Montarville', 9),
 ('PHOENIX', 9),
 ('Chateauguay', 9),
 ('Sagamore Hills', 9),
 ('Mt. Lebanon', 9),
 ('Saint-Lazare', 9),
 ('Glassport', 9),
 ('Rosemere', 8),
 ('las vegas', 8),
 ('Lachute', 8),
 ('Mckeesport', 8),
 ('Mc Donald', 8),
 ('Belle Vernon', 8),
 ('Venetia', 8),
 ('Upper St. Clair', 8),
 ('East Pittsburgh', 8),
 ('Willowdale', 8),
 ('McCandless Township', 8),
 ('Kleinburg', 8),
 ('Fairport Harbor', 8),
 ('Ross Township', 8),
 ('Perry', 8),
 ('Duquesne', 8),
 ('Mascouche', 7),
 ('Hiram', 7),
 ('La Salle', 7),
 ('Blawnox', 7),
 ('Harrison City', 7),
 ('East Cleveland', 7),
 ('Sainte-Anne-De-Bellevue', 7),
 ('Bainbridge', 7),
 ('Cote Saint-Luc', 7),
 ('Northfield Center', 7),
 ('Upper St Clair', 7),
 ('Nobleton', 7),
 ('Oka', 7),
 ('Mount Albert', 7),
 ('Walton Hills', 7),
 ('C√¥te Saint-Luc', 7),
 ('Rouses Point', 7),
 ('Lagrange', 7),
 ('Mirabel', 7),
 ('McAdenville', 7),
 ('Delson', 7),
 ('Dane', 7),
 ('Tottenham', 6),
 ('Mentor On The Lake', 6),
 ('Saint-Constant', 6),
 ('Morin-Heights', 6),
 ('Pitcairn', 6),
 ('Ogden', 6),
 ('Enterprise', 6),
 ('Olmsted Township', 6),
 ('Gormley', 6),
 ('Mont-Saint-Gr√©goire', 6),
 ('Joliette', 6),
 ('Dollard-des Ormeaux', 6),
 ('Oberlin', 6),
 ('Candiac', 6),
 ('Mentor On the', 6),
 ('Vimont', 6),
 ('Rexdale', 6),
 ('Las  Vegas', 5),
 ('LaGrange', 5),
 ('scottsdale', 5),
 ('Arnold', 5),
 ('Mayfield Hts', 5),
 ('Beeton', 5),
 ('Montr√©al-Ouest', 5),
 ('Shadyside', 5),
 ("L'ile-Perrot", 5),
 ('Gates Mills', 5),
 ('Presto', 5),
 ('Kahnawake', 5),
 ('Concord Township', 5),
 ('Bellvue', 5),
 ('Don Mills', 5),
 ('Export', 5),
 ('New Eagle', 5),
 ('Russellton', 5),
 ('Herminie', 5),
 ('Highland Hills', 5),
 ('Clark', 5),
 ('Piedmont', 5),
 ('East McKeesport', 5),
 ('Nellis Air Force Base', 5),
 ('McCandless', 5),
 ('Downsview', 5),
 ('Rio Verde', 5),
 ('mesa', 5),
 ('Rigaud', 5),
 ('Downtown', 5),
 ('Novelty', 5),
 ('Bath', 5),
 ('Lawrenceville', 5),
 ('East Liberty', 4),
 ('Oakland', 4),
 ('Pr√©vost', 4),
 ('charlotte', 4),
 ('Pointe-Aux-Trembles', 4),
 ('Roxboro', 4),
 ('Ormstown', 4),
 ('Hemmingford', 4),
 ('Edgewood', 4),
 ('Port Credit', 4),
 ('Holland Landing', 4),
 ('Saint-Bruno', 4),
 ('Philo', 4),
 ('St-Jerome', 4),
 ('North Olmstead', 4),
 ('Forest Hills', 4),
 ('Rankin', 4),
 ('Malton', 4),
 ('Pheonix', 4),
 ('Library', 4),
 ('Saint-Bernard-de-Lacolle', 4),
 ('Lancaster', 4),
 ('Nellis Afb', 4),
 ('Fox Chapel', 4),
 ('Scottdale', 4),
 ('las Vegas', 4),
 ('Montr√©al-Nord', 4),
 ('King', 4),
 ('Harmarville', 4),
 ('Lachenaie', 4),
 ('St-Leonard', 4),
 ('Sainte-Catherine', 4),
 ('Squirrel Hill', 4),
 ('Montreal-Ouest', 4),
 ('Concord Mills', 4),
 ('Downtown Toronto', 4),
 ('Tolono', 3),
 ('West Elizabeth', 3),
 ('Charlemagne', 3),
 ('Sainte-Genevi√®ve', 3),
 ('Cuddy', 3),
 ('Dollard-Des Ormeaux', 3),
 ('Weston', 3),
 ('Montreal-West', 3),
 ('Beauharnois', 3),
 ('Rawdon', 3),
 ('Emsworth', 3),
 ('Varennes', 3),
 ('Marshall', 3),
 ('Rocky View No. 44', 3),
 ('Homer', 3),
 ('Moon Twp', 3),
 ('Monoroeville', 3),
 ('Sidney', 3),
 ('Northwest Calgary', 3),
 ('Salaberry-De-Valleyfield', 3),
 ('Oakwood', 3),
 ('Wildwood', 3),
 ('Fort Mcdowell', 3),
 ('Southeast Calgary', 3),
 ('Fort mill', 3),
 ('Marvin', 3),
 ('San Diego', 3),
 ('East Mc Keesport', 3),
 ('henderson', 3),
 ('toronto', 3),
 ('Vaudreuil', 3),
 ('Inglewood', 3),
 ('Creighton', 3),
 ('Streetsville', 3),
 ('Salaberry-de-Valleyfield', 3),
 ('Cote-Saint-Luc', 3),
 ('Mentor On the Lake', 3),
 ('pittsburgh', 3),
 ('Franklin Park', 3),
 ('Ingomar', 3),
 ('Brooklyn Heights', 3),
 ('Saint Laurent', 3),
 ('Sainte-Therese', 3),
 ('Division No. 6', 3),
 ('Bloomfield', 3),
 ('Bratenahl', 3),
 ('Warrensville Hts', 3),
 ('Kennedy Township', 3),
 ('Pincourt', 3),
 ('Pointe Claire', 3),
 ('Cuyahoga Fls', 3),
 ('Richmond Hts', 3),
 ('Clarkson', 3),
 ('Paoli', 3),
 ('Central City Village', 2),
 ('Saint-Joseph-du-Lac', 2),
 ('East Mississauga', 2),
 ('Saint-Sauveur-des-Monts', 2),
 ('Rillton', 2),
 ('Noyan', 2),
 ('Eighty Four', 2),
 ('Ft. Mill', 2),
 ('Villa Grove', 2),
 ('Oak Ridges', 2),
 ('Highland Hts', 2),
 ('Pointe-aux-Trembles', 2),
 ('North Braddock', 2),
 ('SCOTTSDALE', 2),
 ('Burlington', 2),
 ('Durham Regional Municipality', 2),
 ('glendale', 2),
 ('Sauk City', 2),
 ('McMurry', 2),
 ('Garfield Hts', 2),
 ('Bainbridge Township', 2),
 ('St-Bruno-de-Montarville', 2),
 ('Sturgeon', 2),
 ('Boston', 2),
 ('South Amherst', 2),
 ('Silver Lake', 2),
 ('Peters Township', 2),
 ('Scarbrough', 2),
 ('Huntsburg', 2),
 ('Montral', 2),
 ('Saint-Basile-le-Grand', 2),
 ('McKnight', 2),
 ('Grand River', 2),
 ('Lowesville', 2),
 ('cleveland', 2),
 ('Agincourt', 2),
 ('Reminderville', 2),
 ('Hamilton', 2),
 ('N. Olmsted', 2),
 ('Green Tree', 2),
 ('Montville', 2),
 ('Phoenix ', 2),
 ('Mississuaga', 2),
 ('Sainte-Genevieve', 2),
 ('Tuscola', 2),
 ('Mt. Holly', 2),
 ('Pointe-Calumet', 2),
 ('Sainte-Anne-des-Plaines', 2),
 ('Kettleby', 2),
 ('South Hills', 2),
 ('CHARLOTTE', 2),
 ('Cuyahoga Heights', 2),
 ("L'ile-Bizard", 2),
 ("L'Assomption", 2),
 ('Thomasboro', 2),
 ('South Las Vegas', 2),
 ('Madison West', 2),
 ('Saint Leonard', 2),
 ('Goodwood', 2),
 ('La Vegas', 2),
 ('Farnham', 2),
 ('Rockyview', 2),
 ('Etobiicoke', 2),
 ('N Ridgeville', 2),
 ("Notre-Dame-de-l'Ile-Perrot", 2),
 ('Brookline', 2),
 ('Pittsburgh ', 2),
 ('Barberton', 2),
 ('Cooksville', 2),
 ('Las Vegas ', 2),
 ('Woodmere Village', 2),
 ('Ontario', 2),
 ('Boston Heights', 2),
 ('Phoenix, AZ', 2),
 ('Fisher', 2),
 ("L'√éle-Bizard", 2),
 ('Las Vegas, NV', 2),
 ('Indian land', 2),
 ('Edmonton', 2),
 ('Plum Boro', 2),
 ('Val-Morin', 2),
 ('Mansfield', 2),
 ('N. Huntingdon', 2),
 ('Neville Island', 2),
 ('Coteau-du-Lac', 2),
 ('Gifford', 2),
 ('Mayfield Hts.', 2),
 ('York Regional Municipality', 2),
 ('Ashburn', 2),
 ('North Charlotte', 2),
 ('Mount Royal', 2),
 ('Mathews', 2),
 ('Crescent', 2),
 ('Montr√®al', 2),
 ('Geauga', 2),
 ('surprise', 2),
 ('Mercier', 2),
 ('Qu√©bec', 2),
 ('Bois-des-Filion', 2),
 ('St Leonard', 2),
 ('Lake Park', 2),
 ('Leslieville', 2),
 ('Montrose', 2),
 ('Saint-Marc-sur-Richelieu', 2),
 ('', 2),
 ('Medina Township', 2),
 ('Chicago', 2),
 ('C√¥te-Saint-Luc', 2),
 ('Ville Saint Laurent', 2),
 ('St. Joseph', 2),
 ('Las Vegas,', 2),
 ('Summerlin South', 2),
 ('Mcfarland', 2),
 ('Maricopa', 2),
 ('Los Angeles', 2),
 ('Napierville', 2),
 ('Shaker Hts', 2),
 ('Bentleyville', 2),
 ('PEORIA', 2),
 ('Lawrence', 2),
 ('Mt Holly', 2),
 ('Broadview Hts', 2),
 ('Saint-Hippolyte', 2),
 ('Sutersville', 2),
 ('North Huntington', 2),
 ('Baldwin', 2),
 ("Baie-d'Urf√©", 2),
 ('Shaler Township', 2),
 ('Sainte-Th√©r√®se-de-Blainville', 2),
 ('Whtiby', 1),
 ('\u200bGilbert', 1),
 ('Ben Avon', 1),
 ('Huntington Beach', 1),
 ('Ville-Marie', 1),
 ('North Carolina', 1),
 ('Warrensville Hts.', 1),
 ('Urbana, Illinois', 1),
 ('montreal', 1),
 ('East Gwillimburry', 1),
 ('Mont St-hilaire', 1),
 ('Montr√©al-West', 1),
 ('Mount Mourne', 1),
 ('Chargrin Falls', 1),
 ('West Valley', 1),
 ('NEWMARKET', 1),
 ('Sunnyslope', 1),
 ('Rockyview County', 1),
 ('Old Town Scottsdale', 1),
 ('St-Clet', 1),
 ('Beltline', 1),
 ('Shady Side', 1),
 ('Greenock', 1),
 ('etobicoke', 1),
 ('Milford', 1),
 ('Pennsylvania', 1),
 ('Port Vue', 1),
 ('COPLEY', 1),
 ('Painesville Township', 1),
 ('Montr√©al (Qu√©bec)', 1),
 ('Berry', 1),
 ('Ballantyne', 1),
 ('Red Mountain', 1),
 ('East Gwilimbury', 1),
 ('North Toronto', 1),
 ('Montreal-Quest', 1),
 ('calgary', 1),
 ('Mentor ohio', 1),
 ('Norval', 1),
 ('Somerton', 1),
 ('Elrama', 1),
 ('Bradford Woods', 1),
 ('cave creek', 1),
 ('Green Valley', 1),
 ('East Hawkesbury', 1),
 ('Sainte-Marguerite-Esterel', 1),
 ('Saint-Sauveur-Des-Monts', 1),
 ('Ansnorveldt', 1),
 ('Spring Hill City View', 1),
 ('Venise-en-Qu√©bec', 1),
 ('110 Las Vegas', 1),
 ('Indian Land,', 1),
 ('Oakwood village', 1),
 ('Medicine Hat', 1),
 ('Vegas', 1),
 ('Greenway', 1),
 ('St.Pittsburgh', 1),
 ('Centennial', 1),
 ('Wilkens Township', 1),
 ('TORONTO - FRONT ST (OT)', 1),
 ('Scottsdale, AZ', 1),
 ('Penn Hills Township', 1),
 ('Rostraver', 1),
 ('Montreal-Est', 1),
 ('canonsburg', 1),
 ('Kingman', 1),
 ('cleveland warrensville bedford', 1),
 ('Mcknight', 1),
 ('Cave creek', 1),
 ('New Tecumseth', 1),
 ('Leeds', 1),
 ('West Las Vegas', 1),
 ('SUN PRAIRIE', 1),
 ('Cuyohoga Falls', 1),
 ('√éle-des-Soeurs', 1),
 ('Mt. Washington', 1),
 ('Bakerstown', 1),
 ('PHOENIX AP', 1),
 ('√éle-Perrot', 1),
 ('cave Creek', 1),
 ('Chomedey, Laval', 1),
 ('Whitney', 1),
 ('Maumee', 1),
 ('Mesa, AZ', 1),
 ('Toronto-Etobicoke', 1),
 ('San Francisco', 1),
 ('University', 1),
 ('Concord Twp', 1),
 ("O'hara Township", 1),
 ('Old Scottsdale', 1),
 ('Midway', 1),
 ('Greenfield-Park', 1),
 ('Auburn Twp', 1),
 ('Markham, ON', 1),
 ('AZ', 1),
 ('Elizabeth Township', 1),
 ('Houston', 1),
 ('Bapchule', 1),
 ('S.Euclid', 1),
 ('Warrensville', 1),
 ('The Promenade', 1),
 ('lyndhurst', 1),
 ('Hartlepool', 1),
 ('University Ht', 1),
 ('kirtland', 1),
 ('Cleveland Hts.', 1),
 ('Phx', 1),
 ('Communaut√©-Urbaine-de-Montr√©al', 1),
 ('Glenwillow', 1),
 ('Cave Creek Road', 1),
 ('Paw Creek', 1),
 ('Pickering Ajax Whitby', 1),
 ('Woodbrigde', 1),
 ('Beachwood ', 1),
 ('HENDERSON', 1),
 ('Henderson Nevada', 1),
 ('MOORESVILLE', 1),
 ('Coteau-Du-Lac', 1),
 ('Lake Mead', 1),
 ('Rainbow Valley', 1),
 ('Fabreville', 1),
 ('Madison East', 1),
 ('Kirlkland', 1),
 ('Parma Hts.', 1),
 ('Richmond Height', 1),
 ('PITTSBURGH', 1),
 ('Mayfield Heights (Cleveland)', 1),
 ('Draper', 1),
 ('Darlington', 1),
 ('Alburgh', 1),
 ('Saint-Pie', 1),
 ('CONCORD', 1),
 ('Mont√©al', 1),
 ('City Center', 1),
 ('Desert Ridge', 1),
 ('East Mesa', 1),
 ('Ahwahtukee', 1),
 ('Newburgh Heights', 1),
 ('Toronto Division', 1),
 ('Down', 1),
 ("Saint-Roch-de-l'Achigan", 1),
 ('N. Randall', 1),
 ('Shaler', 1),
 ('Decatur', 1),
 ('Metro Phoenix', 1),
 ('Suprise', 1),
 ('OAKVILLE', 1),
 ('Scottadale', 1),
 ('Whiitby', 1),
 ('Middleburg', 1),
 ('Chertsey', 1),
 ('Pont-Viau', 1),
 ('N Versailles', 1),
 ('North Las Vegas ', 1),
 ('Ange-Gardien', 1),
 ('Fort Mills', 1),
 ('Bedford Hts.', 1),
 ('Cleveland heights', 1),
 ('Waterloo', 1),
 ('Tornto', 1),
 ('Millcreek', 1),
 ('Hendserson', 1),
 ('Brampton FKA Bramalea', 1),
 ('New Glarus', 1),
 ('Pitsburgh', 1),
 ('Tucson', 1),
 ('markham', 1),
 ('Reno', 1),
 ('Marieville', 1),
 ('W.Mifflin', 1),
 ('Joliet', 1),
 ('Sunrise Manor', 1),
 ('University Hts ', 1),
 ('St-Laurent', 1),
 ('Olmsted', 1),
 ('Sainte- Adele', 1),
 ('Buena Vista', 1),
 ('Henryville', 1),
 ('Cleveland, OH', 1),
 ('Catawba Springs', 1),
 ('Chateau', 1),
 ('North Scottsdale', 1),
 ('Old Brooklyn', 1),
 ('Pittsburch', 1),
 ('Claremont', 1),
 ('W Henderson', 1),
 ('Stanfield', 1),
 ('Alburg', 1),
 ('Strip District', 1),
 ('stoughton', 1),
 ('Les C√®dres', 1),
 ('GILBERT', 1),
 ('Litchfield park', 1),
 ('St Joseph', 1),
 ('Northyork', 1),
 ('Saint-laurent', 1),
 ('W Spring Valley', 1),
 ('Ville Mont-Royal', 1),
 ('Ingram', 1),
 ('Westport', 1),
 ('Quartier des Spectacles', 1),
 ('Ranlo', 1),
 ('Godmanchester', 1),
 ('West Toronto', 1),
 ('Wellington', 1),
 ('Lacolle', 1),
 ('Saint-Esprit', 1),
 ('Fitchburgh', 1),
 ('Ahwatukee Foothills Village', 1),
 ('N.Ridgeville', 1),
 ('Auburn', 1),
 ('Penfield', 1),
 ('Peninsul', 1),
 ('Sunrise', 1),
 ('Mesa Arizona', 1),
 ('LAS VEGAS AP', 1),
 ('Greensboro', 1),
 ('Saint-Isidore-de-Laprairie', 1),
 ('Oakridges', 1),
 ('CALGARY', 1),
 ('Ste-Doroth√©e', 1),
 ('Saintt-Bruno-de-Montarville', 1),
 ('Saint-Basile-Le-Grand', 1),
 ('Maple Hts.', 1),
 ('Peters (Township Of)', 1),
 ('Rock Hill SC', 1),
 ('ROCKY RIVER', 1),
 ('Sun CIty', 1),
 ('Austinburg', 1),
 ('Perry Twp', 1),
 ('CHANDLER', 1),
 ('ETOBICOKE', 1),
 ('Gelndale', 1),
 ('Blakeney', 1),
 ('NORTH YORK', 1),
 ('Mentor on the Lake', 1),
 ('Columbus', 1),
 ('Hnederson', 1),
 ('GLendale', 1),
 ('Saxonburg', 1),
 ('Henderston', 1),
 ('Mississsauga', 1),
 ('Richmond Hil', 1),
 ('Saint-Liboire', 1),

In [3]:
import json
from collections import Counter
from matplotlib import pyplot as plt
import statistics
%matplotlib inline
import gc

In [27]:
jsons = []
with open("../yelp_dataset/yelp_academic_dataset_review.json") as f:
    for i, line in enumerate(f):
        if i >= 2000000:
            jsons.append(json.loads(line))
        if i+1 >= 2600000:
            break
rev = pd.DataFrame(jsons)
rev.head()

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,NxIV6YoOfsiBSxrNF5i1Dw,r5YAim_lxd4Js2gQVGeLsw,T3Bbtht3jO2izyO6f6W8bg,5.0,3,0,4,"Pros: Makaylah: our bartender and server, she ...",2020-10-31 00:18:49
1,S4ULMYax-92NERQvAivrfw,QJIbIcjPb6qhRnb1d4sTjg,EY5cTfLf9BNG3tgoez9fKg,5.0,0,0,0,Authentic and Perfect! \nAs someone who's as b...,2021-02-09 03:12:34
2,uClUShLNMwHJNLgS9J5poQ,IiVjDaSDELbxLIWu0_Ucrw,6nCLoE5WfY69AywtTmg2Lg,5.0,2,0,0,"Great fresh food for lunch, I had the appetize...",2020-10-30 00:04:00
3,3DrBtGCx4N3aXrbpDAxExg,K2vRxDY1uuxtm_YEEfQ9wQ,wMQMMxaGq0HPG0mApezXMw,5.0,1,0,0,I heard good things about Ahi when I moved to ...,2020-05-03 01:21:43
4,uNXSrvw9jO4jarViJcfmvg,ctgPXpW4NitQisBWHaS1YA,5uhG34VRsD0A6lOY8F41Dg,5.0,0,0,1,The Habit is yummy. Had a charburger with chee...,2021-02-09 05:32:37

In [28]:
rev.sort_values('date',ascending=False )

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
54641,CjY4dvNC5Y1m5UpXQCtznA,QKiIQoReb7e6oWYUbeJb_A,Lj0oSzrim8zGPozHbfbLyA,1.0,0,0,0,"Ordered my meal and waited, another person tha...",2022-01-19 19:22:44
126940,DreJTJzwzOBl6THlYl8WOQ,ih2hlbMfrdiJrUTrT48fVQ,KL90USR8vV_fEe__Bhy6Kw,1.0,0,0,0,Owner is a smart a** prick. Bunch of rules on ...,2022-01-19 19:20:27
112147,ckecHffMz-0ZoWwkg2Xdsw,6m-BFhMBOk1W0IA023fnUg,YVy2DgGfNmG5hWYbA7k8jg,5.0,0,0,0,Always friendly at this establishment.\nThe fo...,2022-01-19 19:07:43
120937,5UUxZ4FIRhTmNKew4Y5Z7Q,IcuZF8KioeG-8uXqR4QqPA,KH4fWEKEnFNB7uTVIDUOeQ,1.0,1,0,0,Beware. I depended on this company to get me ...,2022-01-19 19:00:42
110658,nCfYjUYPGaypT9FzCXrhJA,XF6GG8Y_XKESMfU4_vIgHQ,Fyw7Nszsz2E6ZKy7gjPtDw,5.0,3,0,0,Do not let the name of this place fool you - i...,2022-01-19 18:56:22
...,...,...,...,...,...,...,...,...,...
580557,hCgm-d0QEbkDLs2b0IWLpQ,3MYdpmHeNwC6FquRWi3YOg,5YRHE2foNVmv1n8VIJcb-A,3.0,0,0,0,"Sushi was good, not great. They have a nice f...",2005-03-12 18:14:48
60399,fZC7KU3pwo_Zs4H6c6K_6A,58yhbFfNHjULDZx0FD-Dvw,9zlIJ7Q5W4AENjpGgaNSsQ,4.0,0,0,0,Delicious deep dish Chicago-styled pizza. The ...,2005-03-10 05:39:45
130559,cKGt3J4dtIs2otxye0sRrw,58yhbFfNHjULDZx0FD-Dvw,IKMAgK2m6WRIViVFB2vAFQ,3.0,0,0,0,Not the best but decent enough. This is a good...,2005-03-09 07:14:58
130705,zQAx6R3nAZq14qeptM8cCw,58yhbFfNHjULDZx0FD-Dvw,e3CnhtpEVpNISwOAWoxjJg,1.0,2,4,1,More like GHETTO mart. I HATE THIS STORE! Chea...,2005-03-09 03:13:41
130123,5mFl5K_I0Yjz2XX2RiDuMA,58yhbFfNHjULDZx0FD-Dvw,U06ky7tOjrwad_zx05D9yQ,4.0,0,0,0,"This is a good bar to just chill out, drink an...",2005-03-08 05:16:12

In [25]:
df['coordinate'] = df[['latitude','longitude']].apply(tuple, axis=1)

In [31]:
df[df.coordinate.duplicated()].sort_values(by='coordinate')

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours,coordinate
20056,trWcT4Ssc6roDtFceRa2Dg,DeRusso‚Äôs Pizzeria,1120 Pinellas Bayway S,Tierra Verde,FL,33715,27.674873,-82.726579,4.0,81,1,"{'RestaurantsPriceRange2': '2', 'BikeParking':...","Italian, Restaurants, Pizza","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...","(27.6748729, -82.7265795)"
145786,cK-6xqXho6PdLLuLZsi8gA,Going Home Cremations,"1120 S Pinellas Bayway, Ste 202",Tierra Verde,FL,33715,27.674873,-82.726579,5.0,5,1,{'BusinessAcceptsCreditCards': 'True'},"Local Services, Funeral Services & Cemeteries,...","{'Monday': '0:0-23:30', 'Tuesday': '0:0-23:30'...","(27.6748729, -82.7265795)"
70055,cEAjDyP3Zwdz-c3jU0Oq3w,Tierra Verde Property Management,1110 Pinellas Bayway S,Saint Petersburg,FL,33715,27.675726,-82.726385,1.5,6,1,"{'ByAppointmentOnly': 'True', 'BusinessAccepts...","Property Management, Real Estate, Home Services",None,"(27.6757264, -82.726385)"
62451,r9K46WZQ_hCi8vyyHV_tFw,The Brass Monkey,"709 Gulf Way, Ste 1",St. Pete Beach,FL,33706,27.687805,-82.737664,3.5,383,1,"{'Alcohol': 'u'full_bar'', 'RestaurantsTakeOut...","Caribbean, American (Traditional), American (N...","{'Monday': '0:0-0:0', 'Tuesday': '11:30-22:0',...","(27.6878048, -82.7376643)"
127766,hDtwZPO-GFAjrJw2kizgtQ,A Breathe of Fresh Aire,,Ruskin,FL,33570,27.695851,-82.453611,3.5,9,1,"{'BusinessAcceptsCreditCards': 'True', 'ByAppo...","Heating & Air Conditioning/HVAC, Local Service...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...","(27.6958511, -82.4536115)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112368,DoGK8AikBkHpS3gTFXTOZg,Ric's Grill,"The Bruin Centre, 24 Perron Street",St Albert,AB,T8N 1E7,53.634785,-113.626740,2.5,11,0,"{'RestaurantsTakeOut': 'True', 'RestaurantsAtt...","Steakhouses, Burgers, Seafood, Restaurants, Ni...","{'Monday': '11:30-22:0', 'Tuesday': '11:30-22:...","(53.6347855, -113.6267402)"
128869,2-Vb42w1TLOkZNjv2RlMnw,Simply Donairs,388 St Albert Rd,St Albert,AB,T8N 5S8,53.641260,-113.626284,4.5,29,0,"{'WiFi': 'u'no'', 'OutdoorSeating': 'False', '...","Restaurants, Fast Food, Donairs, Middle Easter...","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...","(53.6412597, -113.6262839)"
112154,UiyFIPOSqdvwqcoCSEW3Dw,The Celtic Knot,388 Saint Albert Trail,Saint Albert,AB,T8N 5S8,53.641260,-113.626284,3.5,22,0,"{'RestaurantsReservations': 'True', 'NoiseLeve...","Nightlife, Bars, Pubs","{'Monday': '11:30-0:0', 'Tuesday': '11:30-0:0'...","(53.6412597, -113.6262839)"
71706,YMcXxFQjxJgFkDURLMA-dw,St Louis Bar and Grill,375 Saint Albert Trail,St. Albert,AB,T8N 3K8,53.642721,-113.622506,4.0,10,1,"{'HasTV': 'True', 'RestaurantsTakeOut': 'True'...","Lounges, Bars, Burgers, Restaurants, Nightlife...","{'Monday': '11:30-23:0', 'Tuesday': '11:30-23:...","(53.6427211, -113.622506)"
123102,zt2AxY-0qJ9wU2Ac-MG4yw,St Albert Centre,375 St Albert Trail,St Albert,AB,T8N 3K8,53.642721,-113.622506,3.0,8,1,"{'RestaurantsPriceRange2': '2', 'BusinessParki...","Shopping Centers, Shopping","{'Monday': '10:0-21:0', 'Tuesday': '10:0-21:0'...","(53.6427211, -113.622506)"

In [22]:
df.latitude.nunique()

135593

In [23]:
df.longitude.nunique()

131918

In [14]:
checkin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131930 entries, 0 to 131929
Data columns (total 2 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   business_id  131930 non-null  object
 1   date         131930 non-null  object
dtypes: object(2)
memory usage: 2.0+ MB

In [ ]:
checkin22 = checkin[checkin.date.str.contains('2022')]

In [12]:
checkin.business_id.nunique()

131930

In [6]:
review_json_path = '../yelp_dataset/yelp_academic_dataset_review.json.json'

In [7]:
size = 1000000
review = pd.read_json(review_json_path, lines=True,
                      dtype={'review_id':str,'user_id':str,
                             'business_id':str,'stars':int,
                             'date':str,'text':str,'useful':int,
                             'funny':int,'cool':int},
                      chunksize=size)

In [8]:
review

In [3]:
df.business_id

150346

In [13]:
df[df.is_open==1].count()

business_id     119698
name            119698
address         119698
city            119698
state           119698
postal_code     119698
latitude        119698
longitude       119698
stars           119698
review_count    119698
is_open         119698
attributes      107350
categories      119603
hours           103603
dtype: int64